image: alpine:latest

before_script:
  - apk add --no-cache yarn
  - test -e yarn.lock && yarn

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - public/
    expire_in: 1 day
  only:
    - master

test:
  script:
    - yarn build:dev
  artifacts:
    paths:
      - public/
  except:
    - master
