image: alpine

before_script:
  - apk add --no-cache yarn
  - test -e yarn.lock && yarn

pages:
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
    - master

test:
  script:
    - yarn build:dev
  except:
    - master
